const { chromium } = require('playwright')
const assert = require('node:assert/strict')
;(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 320, height: 740 } })
    const errors = []
    page.on('pageerror', e => errors.push(e.message))
    await page.goto(process.env.VERIFY_URL || 'http://127.0.0.1:4180')
    await page.getByRole('button', { name: '건강', exact: true }).click()
    await page.getByRole('button', { name: '🏋️ 운동', exact: true }).click()
    await page.getByRole('button', { name: '🏃 러닝', exact: true }).click()
    await page.getByRole('button', { name: '계획', exact: true }).click()
    await page.getByRole('button', { name: '계획 저장', exact: true }).click()
    await page.getByText('계획을 저장했습니다.', { exact: false }).waitFor()
    await page.getByRole('button', { name: '기록', exact: true }).click()
    await page.getByLabel('시간 (분)', { exact: true }).fill('32')
    await page.getByLabel('거리 (km, 선택)', { exact: true }).fill('4.1')
    await page.getByRole('button', { name: '러닝 기록 저장' }).click()
    await page.getByText('운동 기록에 저장했습니다.', { exact: true }).waitFor()
    await page.getByRole('button', { name: '오늘', exact: true }).click()
    await page.getByText('실제 러닝 32분', { exact: true }).waitFor()
    assert((await page.locator('body').innerText()).includes('· 완료'))
    await page.getByRole('button', { name: '홈', exact: true }).click()
    await page.getByText('🏃 가벼운 러닝 30분 · 완료', { exact: true }).waitFor()
    await page.getByRole('button', { name: '달력', exact: true }).click()
    await page.getByText('🏃 가벼운 러닝 30분 · 완료', { exact: true }).waitFor()
    assert.equal(errors.length, 0, errors.join('\n'))
    console.log('PASS: 320px 러닝 계획 저장 → 기록 저장 → 자동 완료 → 홈·달력 표시; 페이지 오류 없음')
  } finally { await browser.close() }
})().catch(e => { console.error(e); process.exitCode = 1 })
